name: music
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluro: ^1.4.0
  flutter_screenutil: ^0.5.1
  url_launcher: ^5.0.2
  shared_preferences: ^0.5.1+2
  image_picker: ^0.5.0+9
  dio: ^2.1.0
  flutter_swiper: ^1.1.5
  extended_tabs: ^0.1.4
  provide: ^1.0.2
  audioplayers: ^0.10.1
  flutter_spinkit: ^3.1.0
  extended_image: ^0.2.7
  event_bus: ^1.1.0
  fluttertoast: ^3.0.4





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - asset/image/1.jpg
   - asset/image/3.jpg
   - asset/image/yu.jpg
   - asset/image/ap8.png
   - asset/image/apa.png
   - asset/image/apc.png
   - asset/image/ape.png
   - asset/image/ap.png
   - asset/image/m1.jpg
   - asset/image/m2.jpg
   - asset/image/m3.jpg
   - asset/image/head/n1.jpg
   - asset/image/head/n2.jpg
   - asset/image/head/n3.jpg
   - asset/image/head/n4.jpg
   - asset/image/head/o1.jpg
   - asset/image/head/o2.jpg
   - asset/image/loading/loding1.gif
   - asset/image/loading/loding2.gif
   - asset/image/loading/loding3.gif
   - asset/image/sp.png

   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
        - asset: asset/font/iconfont.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
