class Autogenerated {
  Result result;
  int code;

  Autogenerated({this.result, this.code});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    result =
        json['result'] != null ? new Result.fromJson(json['result']) : null;
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.result != null) {
      data['result'] = this.result.toJson();
    }
    data['code'] = this.code;
    return data;
  }
}

class Result {
  List<Artist> artist;
  List<String> orders;

  Result({this.artist, this.orders});

  Result.fromJson(Map<String, dynamic> json) {
    if (json['artist'] != null) {
      artist = new List<Artist>();
      json['artist'].forEach((v) {
        artist.add(new Artist.fromJson(v));
      });
    }
    orders = json['orders'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.artist != null) {
      data['artist'] = this.artist.map((v) => v.toJson()).toList();
    }
    data['orders'] = this.orders;
    return data;
  }
}

class Artist {
  String name;
  int id;
  int picId;
  int img1v1Id;
  String briefDesc;
  String picUrl;
  String img1v1Url;
  int albumSize;
  List<String> alias;
  String trans;
  int musicSize;
  int mvSize;
  String alg;

  Artist(
      {this.name,
      this.id,
      this.picId,
      this.img1v1Id,
      this.briefDesc,
      this.picUrl,
      this.img1v1Url,
      this.albumSize,
      this.alias,
      this.trans,
      this.musicSize,
      this.mvSize,
      this.alg});

  Artist.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    id = json['id'];
    picId = json['picId'];
    img1v1Id = json['img1v1Id'];
    briefDesc = json['briefDesc'];
    picUrl = json['picUrl'];
    img1v1Url = json['img1v1Url'];
    albumSize = json['albumSize'];
    alias = json['alias'].cast<String>();
    trans = json['trans'];
    musicSize = json['musicSize'];
    mvSize = json['mvSize'];
    alg = json['alg'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['id'] = this.id;
    data['picId'] = this.picId;
    data['img1v1Id'] = this.img1v1Id;
    data['briefDesc'] = this.briefDesc;
    data['picUrl'] = this.picUrl;
    data['img1v1Url'] = this.img1v1Url;
    data['albumSize'] = this.albumSize;
    data['alias'] = this.alias;
    data['trans'] = this.trans;
    data['musicSize'] = this.musicSize;
    data['mvSize'] = this.mvSize;
    data['alg'] = this.alg;
    return data;
  }
}
